Feat: add --no-validate option
dojoengine/dojo pull request #1301
Opened 2023-12-18 13:02 UTC by haroune-mohammedi

2023-12-18 14:36 UTC, glihm commented
Hello @haroune-mohammedi! Thanks for the contribution!

This PR seems to be done with an older version of Katana. Would you mind adjusting the proposition to the new crate layout?

[Here](https://github.com/dojoengine/dojo/blob/fc24a5a23584a847d2a69523671d4926dd899fe7/crates/katana/executor/src/blockifier/mod.rs#L147) is the link of the validate value, which for now is fixed to `true`.

Feel free to reach if you have questions. :+1:

2023-12-22 19:29 UTC, tdelabro commented on crates/katana/core/src/execution.rs
> +    ///
Missing doc

2023-12-22 19:29 UTC, tdelabro requested changes
missing doc

2024-01-03 09:15 UTC, kariy commented
Closing this in favour of #1176

2024-01-03 09:15 UTC, closed without merging