feat: isolate dev JSON RPC API from katana impl
dojoengine/dojo pull request #1544
Opened 2024-02-16 10:51 UTC by makluganteng

2024-02-16 13:51 UTC, kariy requested changes

2024-02-16 13:51 UTC, kariy commented on crates/katana/rpc/rpc/src/dev.rs
> +pub struct DevApiImpl {
can we 
```suggestion
pub struct DevApi {
```

2024-02-16 13:51 UTC, kariy commented on bin/katana/src/args.rs
>          }
```suggestion
        let mut apis = vec![ApiKind::Starknet, ApiKind::Katana];
        
        if self.dev {
            apis.push(ApiKind::Dev);
        }
```

We want to have `starknet` and `katana` available by default. The `--dev` flag should only affect whether `dev` api is included or not.

2024-02-16 13:51 UTC, kariy commented on crates/katana/rpc/rpc/src/dev.rs
> +        unimplemented!()
```suggestion
        Ok(())
```

This already exist before, but while we're at it can we just remove the panic here.

2024-02-16 13:51 UTC, kariy commented on crates/katana/rpc/rpc/src/lib.rs
> +                methods.merge(KatanaApi::new(sequencer.clone()).into_rpc())?;
```suggestion
                methods.merge(DevApi::new(sequencer.clone()).into_rpc())?;
```

Supposed to be the new `DevApiServer` implementation

2024-02-17 04:41 UTC, kariy commented on crates/katana/rpc/rpc-api/src/dev.rs
missed it in my initial review but you haven't deleted the endpoints in [`KatanaApi`](https://github.com/dojoengine/dojo/blob/68e81f65df92837cffcdd4f0b498a3b71edb55a9/crates/katana/rpc/rpc-api/src/katana.rs#L8) which have been moved to `DevApi`

2024-02-17 04:47 UTC, makluganteng commented on crates/katana/rpc/rpc-api/src/dev.rs
Aaa i see so what will be inside the Katana Api ?

2024-02-17 04:49 UTC, kariy commented on crates/katana/rpc/rpc-api/src/dev.rs
Remove all the endpoints that have been moved to `dev` and only keep the `predeployedAccounts` method.

2024-02-17 04:55 UTC, makluganteng commented on crates/katana/rpc/rpc-api/src/dev.rs
done

2024-02-17 05:02 UTC, kariy approved these changes
LGTM, thanks!

2024-02-17 05:04 UTC, makluganteng commented
Thanks serr 🫡

2024-02-17 05:14 UTC, merged