feat: add raw max fee to `TransactionsOptions`
dojoengine/dojo pull request #1856
Opened 2024-04-21 23:46 UTC by princeibs

Closes #1808

2024-04-22 02:51 UTC, glihm reviewed
Good first start @princeibs!
The next step is to implement the max fee being applied in the implementation of the `TransactionExt` trait.

2024-04-22 02:51 UTC, glihm commented on bin/sozo/src/commands/options/transaction.rs
> +    #[arg(long_help = "Maximum raw value to be used for fees. The value is expected to be in wei")]
May we have only one help, as the long one is almost the same?
```
Maximum raw value to be used for fees, in Wei.
```
Something like this?

2024-04-23 08:50 UTC, lambda-0x requested changes
we also need to make sure that user shouldn't be able to specify both `max_fee_raw` and `fee_estimate_multiplier` at the same time. that can be enforced by clap as well a manual check in the trait implementation

2024-04-23 14:26 UTC, glihm commented
> we also need to make sure that user shouldn't be able to specify both `max_fee_raw` and `fee_estimate_multiplier` at the same time. that can be enforced by clap as well a manual check in the trait implementation

Do you know the default behavior of starknet-rs? Because we want to limit that at the command level, no? Or also for the `TransactionExt` we should enforce that?
Or setting the other to 0 is ok to ensure the behavior is not unexpected?

2024-04-23 16:52 UTC, lambda-0x commented
i was under impression that `starknet-rs` doesn't allow specifying both at same time but after looking at its code it seems that it will just ignore `fee_estimate_multiplier` if both of them are specified. so I think we can just use claps to disallow setting both options at same time. And add a comment in implementation that `max_fee` takes precedence in `starknet-rs`.

2024-04-23 17:08 UTC, princeibs commented
It's all cool @lambda-0x. Is the PR ready to be merged or it needs more any more changes?

2024-04-23 17:30 UTC, lambda-0x approved these changes

2024-04-23 17:30 UTC, merged

2024-04-23 17:31 UTC, lambda-0x commented
its done @princeibs, thank you for your contribution!