Display default values for EnvironmentOptions in katana cli
dojoengine/dojo pull request #1861
Opened 2024-04-22 20:11 UTC by notV4l

fixes #1815 

add extra logs at start

```
ENVIRONMENT
==================

| Chain ID            | 0x4b4154414e41
| Disable Fee         | false
| Disable Validate    | false
| Validate max steps  | 1000000
| Invoke max steps    | 1000000
| ETH Gas Price       | 1112701192
| STRK Gas Price      | 0

FORKING
==================
    
| Fork rpc url        | https://api.cartridge.gg/rpc/starknet
| Fork blocknumber    | 42

```

2024-04-24 09:58 UTC, kariy requested changes
im not sure about the prints. i have some idea about displaying the config on startup and the config types are a bit messy right now, so would rather so would prefer if we dont print anything else for now.

2024-04-24 09:58 UTC, kariy commented on bin/katana/src/args.rs
> +    #[arg(default_value = format!("{:?}",DEFAULT_VALIDATE_MAX_STEPS))]
```suggestion
    #[arg(default_value_t = DEFAULT_VALIDATE_MAX_STEPS)]
```

2024-04-24 09:58 UTC, kariy commented on bin/katana/src/args.rs
> +    #[arg(default_value = format!("{:?}",DEFAULT_INVOKE_MAX_STEPS))]
```suggestion
    #[arg(default_value_t = DEFAULT_INVOKE_MAX_STEPS)]
```

2024-04-24 09:58 UTC, kariy commented on bin/katana/src/args.rs
> +    #[arg(default_value = format!("{:?}",DEFAULT_ETH_L1_GAS_PRICE))]
```suggestion
    #[arg(default_value_t = DEFAULT_ETH_L1_GAS_PRICE)]
```

2024-04-24 09:58 UTC, kariy commented on bin/katana/src/args.rs
> +    #[arg(default_value = format!("{:?}",DEFAULT_STRK_L1_GAS_PRICE))]
```suggestion
    #[arg(default_value_t = DEFAULT_STRK_L1_GAS_PRICE)]
```

2024-04-24 09:58 UTC, kariy commented on Cargo.toml
> +clap = { version = "4.5", features = [ "derive", "string" ] }
```suggestion
clap = { version = "4.5", features = [ "derive" ] }
```

2024-04-24 11:06 UTC, notV4l commented on bin/katana/src/args.rs
> +    #[arg(default_value = format!("{:?}",DEFAULT_VALIDATE_MAX_STEPS))]
weird i remind i tried with default_value_t

2024-04-24 11:10 UTC, notV4l commented
> im not sure about the prints. i have some idea about displaying the config on startup and the config types are a bit messy right now, so would rather so would prefer if we dont print anything else for now.

idk why its an issue to diplay more infos but up to you

2024-04-25 06:19 UTC, kariy approved these changes
lgtm

2024-04-25 06:20 UTC, merged