Added chunk size limit to events method
dojoengine/dojo pull request #2644
Opened 2024-11-06 07:12 UTC by PoulavBhowmick03

# Description

This PR adds a Chunk Size Limit to `starknet_getEvents` method

## Related issue

Fixes #2596 

## Tests

- [X] Yes
- [ ] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation?

- [ ] README.md
- [ ] [Dojo Book](https://github.com/dojoengine/book)
- [X] No documentation needed

## Checklist

- [X] I've formatted my code (`scripts/prettier.sh`, `scripts/rust_fmt.sh`, `scripts/cairo_fmt.sh`)
- [ ] I've linted my code (`scripts/clippy.sh`, `scripts/docs.sh`)
- [ ] I've commented my code
- [ ] I've requested a review after addressing the comments

2024-11-06 13:18 UTC, PoulavBhowmick03 commented
@kariy Can you please take a look at this? Thanks!

2024-11-06 15:48 UTC, kariy reviewed
looks good so far. 

just need to make the value configurable from the cli.

2024-11-06 15:48 UTC, kariy commented on crates/katana/rpc/rpc-types/src/error/starknet.rs
> +    ChunkSizeTooBig { requested: u64, maximum: u64 },
we already have an error variant for this 

https://github.com/dojoengine/dojo/blob/0c70748fff67947895f3ff9255ef56ad986a5f41/crates/katana/rpc/rpc-types/src/error/starknet.rs#L34-L35

we can update the `PageSizeTooBig` variant into a struct variant and update the `.data()` function to include the struct fields,

https://github.com/dojoengine/dojo/blob/0c70748fff67947895f3ff9255ef56ad986a5f41/crates/katana/rpc/rpc-types/src/error/starknet.rs#L131-L145

2024-11-06 15:48 UTC, kariy commented on crates/katana/rpc/rpc-types/src/error/starknet.rs
> +            StarknetApiError::ChunkSizeTooBig { .. } => 10001,
remove as per earlier comment

2024-11-06 15:48 UTC, kariy commented on crates/katana/rpc/rpc/src/starknet/mod.rs
> +    max_chunk_size: u64,
lets make this field into an `Option` instead. also maybe lets create a config struct, `StarknetApiConfig`, to encapsulate this value.

2024-11-06 15:48 UTC, kariy commented on crates/katana/rpc/rpc/src/starknet/mod.rs
> +    max_chunk_size: u64,
we should also update all the `StarknetApi::new` functions to accept the new config struct

2024-11-06 15:48 UTC, kariy commented on crates/katana/rpc/rpc/src/starknet/mod.rs
> +    max_chunk_size: u64,
make sure to update the `RpcConfig` with the `max_events_page_size` option

https://github.com/dojoengine/dojo/blob/0c70748fff67947895f3ff9255ef56ad986a5f41/crates/katana/node/src/config/rpc.rs#L20-L28

i think 'page size' is a much better name in this case. maybe we should just call it page size anywhere else and just leave the chunk size name in the server impl.

2024-11-06 15:48 UTC, kariy reviewed
dont forget to add a test for this as well :)

2024-11-06 15:49 UTC, glihm commented on crates/katana/rpc/rpc-types/src/error/starknet.rs
> +            StarknetApiError::ChunkSizeTooBig { .. } => 10001,
We might stick to the spec with `PageSizeTooBig`?
https://github.com/xJonathanLEI/starknet-rs/blob/ee9a5cdd678a3f1941599136432a1502ef772c00/starknet-core/src/types/codegen.rs#L1661

Or @kariy wdyt, are they semantically different?

2024-11-12 22:12 UTC, kariy requested changes

2024-11-12 22:12 UTC, kariy commented on bin/katana/src/cli/node.rs
> +        let page_size = Some(self.server.page_size.min(MAX_PAGE_SIZE));
```suggestion
```

considering we already set a default value in the cli, i think its fine to not have this upper bound. i think we shouldn't impose constraints like this and let the power user do whatever they want with it. im also aware that leaving it unbounded can hurt the performance for user that is unaware of its implications. 

also if user set the value > 10k, this minimization will happen in silent, and thus may not be obvious for the user.

2024-11-13 12:00 UTC, PoulavBhowmick03 commented
@kariy can you PTAL, it is not allowing me to resolve the merge conflicts for some reason, i have made the suggested changes

2024-11-13 15:41 UTC, glihm commented
> @kariy can you PTAL, it is not allowing me to resolve the merge conflicts for some reason, i have made the suggested changes

You can always resolve merge conflicts by pulling the main branch from dojo and merging it into your branch locally. Then you push and your PR will be updated with merge conflicts revolved. 👍

2024-11-14 01:23 UTC, kariy requested changes
all looks good except one small thing.

2024-11-14 01:23 UTC, kariy commented on crates/katana/node/src/lib.rs
> +            max_event_page_size: config.max_event_page_size.or(Some(1000)), // Default value
```suggestion
            max_event_page_size: config.max_event_page_size
```

2024-11-14 01:49 UTC, kariy commented
@PoulavBhowmick03 im happy to merge after the my comments and ci issues are addressed :)

2024-11-14 13:09 UTC, PoulavBhowmick03 commented
@kariy GM! Made the change.

2024-11-14 19:34 UTC, kariy commented
pls run `cargo +nightly-2024-08-28 fmt --all` and `./scripts/clippy.sh`

2024-11-14 19:43 UTC, PoulavBhowmick03 commented
@kariy PTAL. done!

2024-11-15 13:57 UTC, kariy approved these changes

2024-11-15 14:37 UTC, glihm reviewed
Hey @PoulavBhowmick03, nice job on this!
Looks like a test is failing, you would mind trying to run it locally and see the issue if you can reproduce?

2024-11-16 14:26 UTC, glihm commented
> @kariy @glihm there seems to be an error on the torii side? Or is it linked to my pr? Do let me know if it can be merged or do I need to make any changes!

Yeah, seems that torii used a value that is too big. Will have a look later in the day. 👍

2024-11-18 16:08 UTC, merged

2024-11-18 16:08 UTC, PoulavBhowmick03 commented
Any updates on this? :D
@kariy @glihm

2024-11-18 16:22 UTC, kariy commented
> Any updates on this? :D @kariy @glihm

everything was working i just to bump the default value to match what torii was using. so decided to quickly did that :) thanks for the help on this

2024-11-18 19:06 UTC, PoulavBhowmick03 commented
> > Any updates on this? :D @kariy @glihm
> 
> everything was working i just had to bump the default value to match what torii was using in the tests (why it was failing). so decided to quickly did that :) thanks for the help on this

alright! thank you for letting me work on this!